// =============================================================================
// gt_wrapper_stub.sv — BEHAVIOURAL transceiver + PCS model (SIMULATION ONLY)
// -----------------------------------------------------------------------------
// Project : FPGA Algorithmic Trading System (Nasdaq Equities)
// Governs : manuals/01-fpga-design/04-io-transceivers-and-serdes.md
//           manuals/02-networking/01-ethernet-phy-mac.md §1, §2
//
// =============================================================================
// ⚠️⚠️  THIS MODULE IS NOT SYNTHESIZABLE AND MUST NEVER REACH A BITSTREAM.  ⚠️⚠️
// =============================================================================
//   It is instantiated by eth_10g_wrapper.sv ONLY inside `ifdef SIMULATION`.
//   The synthesis build takes gt_wrapper.sv instead — the real GTY/GTH + 10GBASE-R
//   PCS shim generated by the Vivado wizard. If this file ever appears in a
//   synthesis log, the build is wrong: stop and fix the flow, do not "make it
//   synthesize".
//
//   The serial pins are TIED OFF. There is no SerDes here, no CDR, no 64b/66b
//   scrambler, no gearbox, no block lock. Anything that depends on those must be
//   verified on hardware (or against the vendor's own simulation model), not
//   here. See manuals/01-fpga-design/04-io-transceivers-and-serdes.md §9 for
//   what simulation cannot tell you about a real link.
//
// =============================================================================
// WHY IT EXISTS
//   The whole tick-to-trade design must elaborate and run under Verilator with
//   no vendor IP present. This model presents exactly the interface the real
//   gt_wrapper presents — a lane-0-aligned 64-bit XGMII pair plus clocks, resets
//   and link status — so mac_rx / mac_tx / the async FIFOs / net_rx_path / the
//   whole fast path can be driven from a cocotb or C++ testbench.
//
// =============================================================================
// HOW A TESTBENCH DRIVES IT — three ways, pick one
//
//   (1) DIRECT XGMII INJECTION (the normal way)
//       Drive the public variables below by hierarchical reference:
//
//           dut.u_md_eth.g_sim_gt.u_gt.sim_rx_inject <= 1'b1;
//           dut.u_md_eth.g_sim_gt.u_gt.sim_rxd       <= 64'h...;
//           dut.u_md_eth.g_sim_gt.u_gt.sim_rxc       <= 8'h01;
//
//       In cocotb:  dut.u_md_eth.g_sim_gt.u_gt.sim_rxd.value = ...
//       In a Verilator C++ TB the same signals are reachable because they carry
//       /* verilator public_flat_rw */.
//
//       While `sim_rx_inject` is low the model emits continuous /I/ idle, which
//       is what an idle link looks like — so a testbench that does nothing at
//       all still produces a legal, quiet link.
//
//   (2) INTERNAL LOOPBACK (LOOPBACK=1, the default)
//       The XGMII TX stream is fed back to the XGMII RX stream after
//       LOOPBACK_CYCLES cycles. Send a frame with mac_tx and it comes back
//       through mac_rx with a real, correctly-generated FCS. This gives a
//       zero-effort end-to-end self test of preamble/pad/CRC/IFG/terminate
//       handling, and it is how the abort mechanism is verified: assert `abort`
//       on mac_tx and watch mac_rx raise tuser on tlast.
//       Injection (1) takes priority over loopback when sim_rx_inject is high.
//
//   (3) ERROR INJECTION
//       `sim_force_fcs_err` corrupts one byte of every looped-back frame, so the
//       downstream FCS/tuser path can be exercised without hand-building a bad
//       frame. `sim_link_down` drops link_up to test reset sequencing.
//
// =============================================================================
// ⚠️ CLOCKING IN THIS MODEL
//   rx_clk and tx_clk are tied to `free_clk` (which the wrapper drives from
//   core_clk). The whole design is therefore SINGLE-CLOCK in simulation:
//     + Verilator needs no `--timing` and the testbench drives exactly one clock
//     + the async FIFOs still work correctly (identical clocks are a legal case)
//     - the CDC is NOT stressed. Zero ppm offset, zero phase relationship risk.
//
//   ⚠️ CDC correctness is therefore NOT verified by any testbench that uses this
//   model. Per manuals/00-foundations/04-clocking-reset-and-cdc.md §6, CDC needs
//   its own verification: structural CDC lint (Vivado report_cdc) on every
//   build, plus the async FIFO's own testbench run at several clock ratios
//   including nearly-equal frequencies. Do not read a passing simulation here as
//   evidence that the MAC boundary crossing is sound.
//
//   On real hardware the RX datapath runs on the RECOVERED clock with the GT
//   elastic buffer bypassed (LOW_LATENCY=1), saving ~25-60 ns, and TX runs on
//   the local reference clock. See
//   manuals/01-fpga-design/04-io-transceivers-and-serdes.md §7.
//
// LATENCY
//   Not modelled. The real stack is ~40-90 ns RX and ~30-75 ns TX with the
//   elastic buffer bypassed. LOOPBACK_CYCLES exists only to keep the loopback
//   from being combinational; it is not a latency model and must never be used
//   as one. Take the real numbers from the Vivado GT wizard report for the exact
//   configuration and record them in docs/, per
//   manuals/02-networking/01-ethernet-phy-mac.md §9 rule 7.
//
// RESOURCE ESTIMATE
//   Zero. This module does not exist in hardware.
// =============================================================================
`default_nettype none

module gt_wrapper_stub #(
    parameter int unsigned DATA_W          = 64,
    // 1 = feed the XGMII TX stream back into the XGMII RX stream.
    parameter int unsigned LOOPBACK        = 1,
    // Pipeline depth of that loopback. >= 1.
    parameter int unsigned LOOPBACK_CYCLES = 4,
    // Cycles of free_clk before link_up asserts, modelling PCS block lock.
    parameter int unsigned LINK_UP_CYCLES  = 64,
    // Mirrors the wrapper's RX_ONLY: when 1, nothing is transmitted.
    parameter int unsigned RX_ONLY         = 0
) (
    // ── Serial pins. TIED OFF — there is no SerDes in this model. ────────────
    input  var logic                 gt_refclk_p,
    input  var logic                 gt_refclk_n,
    input  var logic                 rxp,
    input  var logic                 rxn,
    output var logic                 txp,
    output var logic                 txn,

    // ── Free-running clock/reset the model builds its domains from ───────────
    input  var logic                 free_clk,
    input  var logic                 free_rst,

    // ── Generated clock/reset domains (see the ⚠️ note above) ────────────────
    output var logic                 rx_clk,
    output var logic                 tx_clk,
    output var logic                 rx_rst,
    output var logic                 tx_rst,

    // ── XGMII, lane-0-aligned starts (the contract mac_rx/mac_tx rely on) ────
    output var logic [DATA_W-1:0]    xgmii_rxd,
    output var logic [DATA_W/8-1:0]  xgmii_rxc,
    input  var logic [DATA_W-1:0]    xgmii_txd,
    input  var logic [DATA_W/8-1:0]  xgmii_txc,

    // ── Link status, all in the rx_clk domain ────────────────────────────────
    output var logic                 link_up,
    output var logic                 block_lock,
    output var logic                 hi_ber,
    output var logic                 local_fault,
    output var logic                 remote_fault
);

    localparam int unsigned KEEP_W = DATA_W / 8;
    localparam logic [7:0]  XGMII_IDLE = 8'h07;
    localparam logic [DATA_W-1:0] IDLE_BEAT = {KEEP_W{XGMII_IDLE}};
    localparam int unsigned LB_DEPTH = (LOOPBACK_CYCLES < 1) ? 1 : LOOPBACK_CYCLES;

    // -------------------------------------------------------------------------
    // Serial pins: unused. Consume them so lint stays clean, and hold TX quiet —
    // the market-data link is RX-only and its TX is "held quiet" per fpga_top.
    // -------------------------------------------------------------------------
    /* verilator lint_off UNUSED */
    wire unused_serial = gt_refclk_p ^ gt_refclk_n ^ rxp ^ rxn;
    /* verilator lint_on UNUSED */
    assign txp = 1'b0;
    assign txn = 1'b1;

    // -------------------------------------------------------------------------
    // Clock domains. See the ⚠️ CLOCKING note in the header.
    // -------------------------------------------------------------------------
    assign rx_clk = free_clk;
    assign tx_clk = free_clk;

    // =========================================================================
    // TESTBENCH INJECTION INTERFACE
    // Plain variables, not ports, so eth_10g_wrapper's port list stays exactly
    // as fpga_top.sv declares it. Reachable by hierarchical reference from any
    // SystemVerilog / cocotb testbench, and from Verilator C++ via the public
    // pragmas.
    // =========================================================================
    logic                sim_rx_inject     /* verilator public_flat_rw */;
    logic [DATA_W-1:0]   sim_rxd           /* verilator public_flat_rw */;
    logic [KEEP_W-1:0]   sim_rxc           /* verilator public_flat_rw */;
    logic                sim_link_down     /* verilator public_flat_rw */;
    logic                sim_force_fcs_err /* verilator public_flat_rw */;

    initial begin
        sim_rx_inject     = 1'b0;
        sim_rxd           = IDLE_BEAT;
        sim_rxc           = {KEEP_W{1'b1}};
        sim_link_down     = 1'b0;
        sim_force_fcs_err = 1'b0;
    end

    // =========================================================================
    // Reset synchronization into the generated domains.
    // Trivial here because rx_clk == tx_clk == free_clk, but kept explicit so
    // the model has the same reset shape as the real gt_wrapper: a GT-sourced
    // reset that stays asserted until the link is usable.
    // =========================================================================
    logic [1:0] rst_pipe;
    always_ff @(posedge free_clk) begin
        if (free_rst) begin
            rst_pipe <= 2'b11;
        end else begin
            rst_pipe <= {rst_pipe[0], 1'b0};
        end
    end
    assign rx_rst = rst_pipe[1] | sim_link_down;
    assign tx_rst = rst_pipe[1];

    // =========================================================================
    // Link bring-up model: block lock after LINK_UP_CYCLES, then link_up.
    // =========================================================================
    localparam int unsigned LU_W = (LINK_UP_CYCLES < 2) ? 2 : $clog2(LINK_UP_CYCLES + 1);
    logic [LU_W-1:0] lu_cnt;

    always_ff @(posedge free_clk) begin
        if (free_rst) begin
            lu_cnt     <= '0;
            block_lock <= 1'b0;
        end else begin
            if (sim_link_down) begin
                lu_cnt     <= '0;
                block_lock <= 1'b0;
            end else if (lu_cnt < LU_W'(LINK_UP_CYCLES)) begin
                lu_cnt     <= lu_cnt + LU_W'(1);
                block_lock <= 1'b0;
            end else begin
                block_lock <= 1'b1;
            end
        end
    end

    assign link_up      = block_lock && !sim_link_down;
    assign hi_ber       = 1'b0;
    assign local_fault  = !block_lock;
    assign remote_fault = 1'b0;

    // =========================================================================
    // Loopback pipeline: XGMII TX -> XGMII RX, LB_DEPTH cycles later.
    // =========================================================================
    logic [DATA_W-1:0] lb_d [LB_DEPTH];
    logic [KEEP_W-1:0] lb_c [LB_DEPTH];

    always_ff @(posedge free_clk) begin
        if (free_rst) begin
            for (int unsigned i = 0; i < LB_DEPTH; i++) begin
                lb_d[i] <= IDLE_BEAT;
                lb_c[i] <= {KEEP_W{1'b1}};
            end
        end else begin
            // Stage 0 takes the TX beat. ⚠️ sim_force_fcs_err flips one bit of
            // every DATA beat, which corrupts the payload without touching the
            // control lanes — the frame still delineates correctly and fails
            // only its FCS, which is exactly the case the tuser path must catch.
            lb_d[0] <= (RX_ONLY != 0)                     ? IDLE_BEAT
                     : (sim_force_fcs_err && (xgmii_txc == '0))
                                                          ? (xgmii_txd ^ {{(DATA_W-1){1'b0}}, 1'b1})
                                                          : xgmii_txd;
            lb_c[0] <= (RX_ONLY != 0) ? {KEEP_W{1'b1}} : xgmii_txc;

            for (int unsigned i = 1; i < LB_DEPTH; i++) begin
                lb_d[i] <= lb_d[i-1];
                lb_c[i] <= lb_c[i-1];
            end
        end
    end

    // =========================================================================
    // RX stream select. Injection wins; then loopback; otherwise idle.
    // Registered, so the wrapper sees a clean XGMII bus.
    // =========================================================================
    logic [DATA_W-1:0] rxd_d;
    logic [KEEP_W-1:0] rxc_d;

    always_comb begin
        rxd_d = IDLE_BEAT;                      // default: quiet link, no latch
        rxc_d = {KEEP_W{1'b1}};
        if (sim_link_down) begin
            rxd_d = IDLE_BEAT;
            rxc_d = {KEEP_W{1'b1}};
        end else if (sim_rx_inject) begin
            rxd_d = sim_rxd;
            rxc_d = sim_rxc;
        end else if (LOOPBACK != 0) begin
            rxd_d = lb_d[LB_DEPTH-1];
            rxc_d = lb_c[LB_DEPTH-1];
        end
    end

    always_ff @(posedge free_clk) begin
        if (free_rst) begin
            xgmii_rxd <= IDLE_BEAT;
            xgmii_rxc <= {KEEP_W{1'b1}};
        end else begin
            xgmii_rxd <= rxd_d;
            xgmii_rxc <= rxc_d;
        end
    end

    // =========================================================================
    // Loud reminder, once, at elaboration.
    // =========================================================================
`ifndef SYNTHESIS
    initial begin : b_banner
        $display("[gt_wrapper_stub] %m: BEHAVIOURAL GT/PCS MODEL — NOT SYNTHESIZABLE. loopback=%0d rx_only=%0d",
                 LOOPBACK, RX_ONLY);
    end
`else
    // If this ever elaborates under synthesis the flow is broken.
    initial begin : b_synth_guard
        $fatal(1, "gt_wrapper_stub instantiated in a SYNTHESIS build — use gt_wrapper.sv");
    end
`endif

endmodule : gt_wrapper_stub

`default_nettype wire
